name: Deploy Filth Lang Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Filth Lang site
        run: bun run build:site

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: github-actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/filth
            git fetch origin
            git checkout main
            git pull origin main
            # Install Bun
            curl -fsSL https://bun.sh/install | bash
            # Add Bun to PATH
            export BUN_INSTALL="/home/github-actions/.bun"
            export PATH="/home/github-actions/.bun/bin:$PATH"
            # Install dependencies and build
            bun install
            bun run build:site
